# Constants

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
PLAYER_START_X = SCREEN_WIDTH // 2
PLAYER_START_Y = SCREEN_HEIGHT - 100
ENEMY_START_Y_MIN = 50 # 50 -150 px 
ENEMY_START_Y_MAX = 150
ENEMY_SPEED_X = 4 # no of steps
ENEMY_SPEED_Y = 20
BULLET_SPEED_Y = 10
IMG_HEIGHT = 50 # for scaling images
IMG_WIDTH = 50
MAX_Y_ALLOWED_ENEMY = 340 
RESET_ENEMIES_POSITION = 2000